### ISSUE TITLE
请问键盘是用不了吗？

### ISSUE THREAD

**Issue by xiaoMGitHub** [Snarler95/Acer-S50-51-hackintosh#1]
我装了11.1，键盘似乎是识别不了

**Comment by Snarler95** [comment]
也不能说识别不了，可以识别的。但是你需要用一个带usb的键盘插入你的笔记本，然后按下键盘的徽标键+大写键。 之后你就可以正常使用了。目前还在寻找解决方法中

**Comment by xiaoMGitHub** [comment]
这么奇葩，触控板有啥问题？我看了下是i2c的设备
